<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DNID0694L01" ignored="0" name="Default test" tests="15" failures="1" timestamp="14 Jun 2020 14:33:44 GMT" time="135.918" errors="0">
  <testcase name="testPromotionVouchers" time="5.663" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="testPromotionVouchers" time="3.937" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="testPromotionVouchers" time="4.203" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="testPromotionVouchers" time="4.069" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="testPromotionVouchers" time="4.296" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkData" time="0.14" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkData" time="0.001" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkData" time="0.001" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkData" time="0.009" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkData" time="0.001" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkDB" time="5.42" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkDB" time="4.019" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkDB" time="0.002" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
  <testcase name="checkDB" time="5.149" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion">
    <failure type="java.lang.AssertionError" message="expected [1] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [7]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at remoteService.promotion.TC_Remote_Service_GetVoucherPromotion.checkDB(TC_Remote_Service_GetVoucherPromotion.java:171)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDB -->
  <testcase name="checkDB" time="0.001" classname="remoteService.promotion.TC_Remote_Service_GetVoucherPromotion"/>
</testsuite> <!-- Default test -->
