<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DNID0694L01" ignored="0" name="Default test" tests="3" failures="0" timestamp="16 Jun 2020 08:11:30 GMT" time="0.101" errors="0">
  <testcase name="@BeforeClass beforeClass" time="0.004" classname="remoteService.order.TC_Remote_Service_GetRecentNumber">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at remoteService.order.TC_Remote_Service_GetRecentNumber.beforeClass(TC_Remote_Service_GetRecentNumber.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass beforeClass -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="remoteService.order.TC_Remote_Service_GetRecentNumber">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="testRecentNumber" time="0.0" classname="remoteService.order.TC_Remote_Service_GetRecentNumber">
    <skipped/>
  </testcase> <!-- testRecentNumber -->
  <testcase name="checkData" time="0.0" classname="remoteService.order.TC_Remote_Service_GetRecentNumber">
    <skipped/>
  </testcase> <!-- checkData -->
  <testcase name="checkDB" time="0.0" classname="remoteService.order.TC_Remote_Service_GetRecentNumber">
    <skipped/>
  </testcase> <!-- checkDB -->
</testsuite> <!-- Default test -->
