<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="DANA Pulsa Suite" duration-ms="139337" started-at="2020-06-20T07:53:28Z" finished-at="2020-06-20T07:55:47Z">
    <groups>
    </groups>
    <test name="DanaPulsaTestIntegrationVoucher" duration-ms="139337" started-at="2020-06-20T07:53:28Z" finished-at="2020-06-20T07:55:47Z">
      <class name="integrationtest.voucher.TC_Integration_VoucherRecommendation">
        <test-method status="PASS" signature="setup()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="setup" is-config="true" duration-ms="30" started-at="2020-06-20T07:53:28Z" finished-at="2020-06-20T07:53:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="beforeClass" is-config="true" duration-ms="37710" started-at="2020-06-20T07:53:28Z" finished-at="2020-06-20T07:54:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="testRecommendationVouchers()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@548e6d58]" name="testRecommendationVouchers" duration-ms="8934" started-at="2020-06-20T07:54:05Z" finished-at="2020-06-20T07:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRecommendationVouchers -->
        <test-method status="PASS" signature="checkData()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@548e6d58]" name="checkData" duration-ms="16" started-at="2020-06-20T07:54:14Z" depends-on-methods="integrationtest.voucher.TC_Integration_VoucherRecommendation.testRecommendationVouchers" finished-at="2020-06-20T07:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkData -->
        <test-method status="PASS" signature="checkDB()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@548e6d58]" name="checkDB" duration-ms="4556" started-at="2020-06-20T07:54:14Z" depends-on-methods="integrationtest.voucher.TC_Integration_VoucherRecommendation.checkData" finished-at="2020-06-20T07:54:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDB -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="afterClass" is-config="true" duration-ms="19965" started-at="2020-06-20T07:54:19Z" finished-at="2020-06-20T07:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="setup" is-config="true" duration-ms="1" started-at="2020-06-20T07:54:39Z" finished-at="2020-06-20T07:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="beforeClass" is-config="true" duration-ms="29393" started-at="2020-06-20T07:54:39Z" finished-at="2020-06-20T07:55:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testRecommendationVouchers()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="testRecommendationVouchers" duration-ms="15877" started-at="2020-06-20T07:55:08Z" finished-at="2020-06-20T07:55:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<500> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<500> but was:<200>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at base.TestBase.checkStatusCode(TestBase.java:165)
at integrationtest.voucher.TC_Integration_VoucherRecommendation.testRecommendationVouchers(TC_Integration_VoucherRecommendation.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRecommendationVouchers -->
        <test-method status="SKIP" signature="checkData()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="checkData" duration-ms="0" started-at="2020-06-20T07:55:24Z" depends-on-methods="integrationtest.voucher.TC_Integration_VoucherRecommendation.testRecommendationVouchers" finished-at="2020-06-20T07:55:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_Integration_VoucherRecommendation.checkData()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_Integration_VoucherRecommendation.checkData()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkData -->
        <test-method status="SKIP" signature="checkDB()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="checkDB" duration-ms="0" started-at="2020-06-20T07:55:24Z" depends-on-methods="integrationtest.voucher.TC_Integration_VoucherRecommendation.checkData" finished-at="2020-06-20T07:55:24Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_Integration_VoucherRecommendation.checkDB()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_Integration_VoucherRecommendation.checkDB()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDB -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:integrationtest.voucher.TC_Integration_VoucherRecommendation@623a8092]" name="afterClass" is-config="true" duration-ms="22821" started-at="2020-06-20T07:55:24Z" finished-at="2020-06-20T07:55:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- integrationtest.voucher.TC_Integration_VoucherRecommendation -->
    </test> <!-- DanaPulsaTestIntegrationVoucher -->
  </suite> <!-- DANA Pulsa Suite -->
</testng-results>
